### ISSUE TITLE
Reload dock database service is created only if initialization of the dock database fails.

### ISSUE THREAD

**Issue by Plaqueoff** [open-navigation/opennav_docking#45]
The reload dock database service is created [here](https://github.com/open-navigation/opennav_docking/blob/a3b14ff82a5866dc46f068758d5318c287eb1019/opennav_docking/src/dock_database.cpp#L45) just under where the initialize method returns true, so it is not created if initialization succeeds.

**Comment by SteveMacenski** [comment]
Fixed in Nav2 migration https://github.com/ros-navigation/navigation2/tree/main/nav2_docking

**Comment by SteveMacenski** [comment]
Backported to humble now
